name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources/
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Server Image
        run: |
          docker build -t ${{ secrets.SERVER_IMAGE_TAG }} .
          docker push ${{ secrets.SERVER_IMAGE_TAG }}

      - name: Build and Push Client Image
        run: |
          docker build -t ${{ secrets.CLIENT_IMAGE_TAG }} ./frontend
          docker push ${{ secrets.CLIENT_IMAGE_TAG }}
  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: SSH to deploy server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_SERVER_IP }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            cd ${{ secrets.REMOTE_SERVER_PATH }}
            docker pull ${{ secrets.SERVER_IMAGE_TAG }}
            docker pull ${{ secrets.CLIENT_IMAGE_TAG }}
            docker compose down
            docker system prune -f
            docker compose up --build -d
