name: Pull Request Check

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'frontend/**'

jobs:
  verify-server:
    runs-on: ubuntu-latest
    if: github.event.head_commit == null || contains(github.event.head_commit.modified, 'src/')
    steps:
      - uses: actions/checkout@v4

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources/
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Server Image
        run: |
          docker build -t test-sever:latest .

  verify-client:
    runs-on: ubuntu-latest
    if: github.event.head_commit == null || contains(github.event.head_commit.modified, 'frontend/')
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Client Image
        run: |
          docker build -t test-client:latest ./frontend

